import os
from crewai.tools import tool

@tool("File Writer Tool")
def write_file(file_path: str, content: str) -> str:
    """
    Writes the given code content to a file at the specified file_path.
    Always use this tool to save the final code generated by the Coder.
    """
    try:
        # Create a safe output directory in the root of your project
        safe_dir = os.path.join(os.getcwd(), 'modernized_output')
        
        # Combine the safe directory with the requested file path
        full_path = os.path.join(safe_dir, file_path)
        
        # Create any necessary sub-folders automatically
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        
        # Write the file
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        return f"Success! File created at {full_path}"
    except Exception as e:
        return f"Error writing file {file_path}: {str(e)}"